title: Robert R. Ford
description: Atmospheric science graduate student at the University at Albany
author: Robert R. Ford
email: rford@albany.edu
github: r-ford
theme: jekyll-theme-minimal
markdown: kramdown
